stages:
    - build
    - push

default:
    before_script:
        - docker info
        - echo -n $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY

Build:
    stage: build
    script:
        - >
          docker build 
          --tag $REGISTRY/fibers-ltd-v2:latest
          --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
          --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
          --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
          --tag $REGISTRY/fibers-ltd-v2:$CI_COMMIT_SHA:$CI_COMMIT_SHA
          .
        - docker push $REGISTRY/fibers-ltd-v2:$CI_COMMIT_SHA

Push latest:
    variables:
        GIT_STRATEGY: none
    stage: push
    only:
        - master
    script:
        - docker pull $REGISTRY/fibers-ltd-v2:$CI_COMMIT_SHA
        - docker tag  $REGISTRY/fibers-ltd-v2:$CI_COMMIT_SHA $REGISTRY/fibers-ltd-v2:latest
        - docker push $REGISTRY/fibers-ltd-v2:latest

